loading

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/raw/INvideos.csv")

In [3]:
df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,kzwfHumJyYc,17.14.11,Sharry Mann: Cute Munda ( Song Teaser) | Parmi...,Lokdhun Punjabi,1,2017-11-12T12:20:39.000Z,"sharry mann|""sharry mann new song""|""sharry man...",1096327,33966,798,882,https://i.ytimg.com/vi/kzwfHumJyYc/default.jpg,False,False,False,Presenting Sharry Mann latest Punjabi Song Cu...
1,zUZ1z7FwLc8,17.14.11,"पीरियड्स के समय, पेट पर पति करता ऐसा, देखकर दं...",HJ NEWS,25,2017-11-13T05:43:56.000Z,"पीरियड्स के समय|""पेट पर पति करता ऐसा""|""देखकर द...",590101,735,904,0,https://i.ytimg.com/vi/zUZ1z7FwLc8/default.jpg,True,False,False,"पीरियड्स के समय, पेट पर पति करता ऐसा, देखकर दं..."
2,10L1hZ9qa58,17.14.11,Stylish Star Allu Arjun @ ChaySam Wedding Rece...,TFPC,24,2017-11-12T15:48:08.000Z,Stylish Star Allu Arjun @ ChaySam Wedding Rece...,473988,2011,243,149,https://i.ytimg.com/vi/10L1hZ9qa58/default.jpg,False,False,False,Watch Stylish Star Allu Arjun @ ChaySam Weddin...
3,N1vE8iiEg64,17.14.11,Eruma Saani | Tamil vs English,Eruma Saani,23,2017-11-12T07:08:48.000Z,"Eruma Saani|""Tamil Comedy Videos""|""Films""|""Mov...",1242680,70353,1624,2684,https://i.ytimg.com/vi/N1vE8iiEg64/default.jpg,False,False,False,This video showcases the difference between pe...
4,kJzGH0PVQHQ,17.14.11,why Samantha became EMOTIONAL @ Samantha naga ...,Filmylooks,24,2017-11-13T01:14:16.000Z,"Filmylooks|""latest news""|""telugu movies""|""telu...",464015,492,293,66,https://i.ytimg.com/vi/kJzGH0PVQHQ/default.jpg,False,False,False,why Samantha became EMOTIONAL @ Samantha naga ...

In [4]:
df.shape

(37352, 16)

In [5]:
df.columns.tolist()

['video_id',
 'trending_date',
 'title',
 'channel_title',
 'category_id',
 'publish_time',
 'tags',
 'views',
 'likes',
 'dislikes',
 'comment_count',
 'thumbnail_link',
 'comments_disabled',
 'ratings_disabled',
 'video_error_or_removed',
 'description']

In [6]:
df.dtypes

video_id                    str
trending_date               str
title                       str
channel_title               str
category_id               int64
publish_time                str
tags                        str
views                     int64
likes                     int64
dislikes                  int64
comment_count             int64
thumbnail_link              str
comments_disabled          bool
ratings_disabled           bool
video_error_or_removed     bool
description                 str
dtype: object

In [7]:
df.describe()

        category_id         views         likes      dislikes  comment_count
count  37352.000000  3.735200e+04  3.735200e+04  3.735200e+04    37352.00000
mean      21.576596  1.060478e+06  2.708272e+04  1.665082e+03     2676.99743
std        6.556593  3.184932e+06  9.714510e+04  1.607617e+04    14868.31713
min        1.000000  4.024000e+03  0.000000e+00  0.000000e+00        0.00000
25%       23.000000  1.239155e+05  8.640000e+02  1.080000e+02       81.00000
50%       24.000000  3.045860e+05  3.069000e+03  3.260000e+02      329.00000
75%       24.000000  7.992912e+05  1.377425e+04  1.019250e+03     1285.00000
max       43.000000  1.254322e+08  2.912710e+06  1.545017e+06   827755.00000

In [8]:
df["video_id"].nunique()

16307

In [9]:
important_columns = [
    "video_id",
    "title",
    "channel_title",
    "category_id",
    "publish_time",
    "trending_date",
    "views",
    "likes",
    "dislikes",
    "comment_count",
    "tags"
]

print("Important columns:")
print(important_columns)

Important columns:
['video_id', 'title', 'channel_title', 'category_id', 'publish_time', 'trending_date', 'views', 'likes', 'dislikes', 'comment_count', 'tags']